/*
=====================================================
PROJECT: CUSTOMER BEHAVIOR ANALYSIS
=====================================================
DESCRIPTION:
This SQL project analyzes customer purchasing behavior,
revenue patterns, discount usage, subscription trends,
shipping preferences, and customer segmentation.

TOOLS & CONCEPTS USED:
- MySQL
- Aggregate Functions
- Subqueries
- CTEs

OBJECTIVE:
To derive business insights from customer transaction data
and support data-driven decision making.
=====================================================
*/


CREATE DATABASE customer_behavior_analysis;

USE customer_behavior_analysis;

SHOW TABLES;

SELECT *
FROM customer
LIMIT 20;
-- Insight: Displays the first 20 records from the customer table for quick data preview.

-- What is the total revenue geneatate by male vs female customers
SELECT 
    gender, SUM(purchase_amount) AS total_revenue
FROM
    customer
GROUP BY gender;
--  Insight: Compares total sales revenue generated by male and female customers.

-- Which customers used a discount but still spent more than the average purchase amount? 
SELECT 
    customer_id, purchase_amount
FROM
    customer
WHERE
    discount_applied = 'Yes'
        AND purchase_amount >= (SELECT 
            AVG(purchase_amount) AS price
        FROM
            customer);
-- Insight: Identifies high-spending customers who still used discounts during purchases. 

-- Which are the top 5 products with the highest average review rating?
SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS rating_product_rating
FROM
    customer
GROUP BY item_purchased
ORDER BY rating_product_rating DESC
LIMIT 5;
-- Insight: Finds the products receiving the best customer review ratings.

-- Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT 
    shipping_type, ROUND(AVG(purchase_amount), 2) AS avg_price
FROM
    customer
WHERE
    shipping_type IN ('Standard' , 'Express')
GROUP BY shipping_type;
-- Insight: Compares customer spending based on shipping method selection.

-- Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM
    customer
GROUP BY subscription_status
ORDER BY total_revenue , avg_spend DESC;
-- Insight: Shows whether subscribed customers contribute more revenue than non-subscribers.

-- Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    ROUND(100.0 * SUM(CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END) / COUNT(*),
            2) AS discount_rate
FROM
    customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;
-- Insight: Identifies products most frequently purchased using discounts.

-- Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

SELECT 
    customer_segment, COUNT(*) AS 'Number of Customers'
FROM
    customer_type
GROUP BY customer_segment;
-- Insight: Classifies customers into New, Returning, and Loyal groups based on purchase history.

-- What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT 
    item_rank, category, item_purchased, total_orders
FROM
    item_counts
WHERE
    item_rank <= 3;
-- Insight: Finds the best-selling products within each product category.

-- Are customers who are repeat buyers (more than 5 previous purchases) 
-- also likely to subscribe?
SELECT 
    subscription_status, COUNT(customer_id) AS repeat_buyers
FROM
    customer
WHERE
    previous_purchases > 5
GROUP BY subscription_status;
-- Insight: Analyzes whether repeat customers are more likely to subscribe.
 
-- What is the revenue contribution of each age group? 
SELECT 
    age_group, SUM(purchase_amount) AS total_revenue
FROM
    customer
GROUP BY age_group
ORDER BY total_revenue DESC;
-- Insight: Shows which age groups contribute the highest sales revenue. 